async function fetcher(url: string) {
  const res = await fetch(url);
  const data = await res.json();
  return data;
}

export function get10CountriesStartFrom(index: number) {
  return COUNTRIES.slice(index, index + 10);
}
export function getRandom10Countries() {
  const randomCountries = [];
  for (let i = 0; i < 10; i++) {
    const randomIndex = Math.floor(Math.random() * COUNTRIES.length);
    randomCountries.push(COUNTRIES[randomIndex]);
  }
  return randomCountries;
}
export type TCountry = {
  id: string;
  name: string;
  capital: string;
  flag: string;
};
export const COUNTRIES: TCountry[] = [
  {
    id: "TGO",
    name: "Togo",
    capital: "Lomé",
    flag: "https://flagcdn.com/w320/tg.png",
  },
  {
    id: "MYT",
    name: "Mayotte",
    capital: "Mamoudzou",
    flag: "https://flagcdn.com/w320/yt.png",
  },
  {
    id: "GEO",
    name: "Georgia",
    capital: "Tbilisi",
    flag: "https://flagcdn.com/w320/ge.png",
  },
  {
    id: "VUT",
    name: "Vanuatu",
    capital: "Port Vila",
    flag: "https://flagcdn.com/w320/vu.png",
  },
  {
    id: "KGZ",
    name: "Kyrgyzstan",
    capital: "Bishkek",
    flag: "https://flagcdn.com/w320/kg.png",
  },
  {
    id: "NER",
    name: "Niger",
    capital: "Niamey",
    flag: "https://flagcdn.com/w320/ne.png",
  },
  {
    id: "CHN",
    name: "China",
    capital: "Beijing",
    flag: "https://flagcdn.com/w320/cn.png",
  },
  {
    id: "TUV",
    name: "Tuvalu",
    capital: "Funafuti",
    flag: "https://flagcdn.com/w320/tv.png",
  },
  {
    id: "COM",
    name: "Comoros",
    capital: "Moroni",
    flag: "https://flagcdn.com/w320/km.png",
  },
  {
    id: "BIH",
    name: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    flag: "https://flagcdn.com/w320/ba.png",
  },
  {
    id: "BHR",
    name: "Bahrain",
    capital: "Manama",
    flag: "https://flagcdn.com/w320/bh.png",
  },
  {
    id: "SOM",
    name: "Somalia",
    capital: "Mogadishu",
    flag: "https://flagcdn.com/w320/so.png",
  },
  {
    id: "BLM",
    name: "Saint Barthélemy",
    capital: "Gustavia",
    flag: "https://flagcdn.com/w320/bl.png",
  },
  {
    id: "LVA",
    name: "Latvia",
    capital: "Riga",
    flag: "https://flagcdn.com/w320/lv.png",
  },
  {
    id: "CYM",
    name: "Cayman Islands",
    capital: "George Town",
    flag: "https://flagcdn.com/w320/ky.png",
  },
  {
    id: "NLD",
    name: "Netherlands",
    capital: "Amsterdam",
    flag: "https://flagcdn.com/w320/nl.png",
  },
  {
    id: "LSO",
    name: "Lesotho",
    capital: "Maseru",
    flag: "https://flagcdn.com/w320/ls.png",
  },
  {
    id: "VEN",
    name: "Venezuela",
    capital: "Caracas",
    flag: "https://flagcdn.com/w320/ve.png",
  },
  {
    id: "KEN",
    name: "Kenya",
    capital: "Nairobi",
    flag: "https://flagcdn.com/w320/ke.png",
  },
  {
    id: "TUR",
    name: "Turkey",
    capital: "Ankara",
    flag: "https://flagcdn.com/w320/tr.png",
  },
  {
    id: "FJI",
    name: "Fiji",
    capital: "Suva",
    flag: "https://flagcdn.com/w320/fj.png",
  },
  {
    id: "TTO",
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    flag: "https://flagcdn.com/w320/tt.png",
  },
  {
    id: "HND",
    name: "Honduras",
    capital: "Tegucigalpa",
    flag: "https://flagcdn.com/w320/hn.png",
  },
  {
    id: "JEY",
    name: "Jersey",
    capital: "Saint Helier",
    flag: "https://flagcdn.com/w320/je.png",
  },
  {
    id: "DJI",
    name: "Djibouti",
    capital: "Djibouti",
    flag: "https://flagcdn.com/w320/dj.png",
  },
  {
    id: "REU",
    name: "Réunion",
    capital: "Saint-Denis",
    flag: "https://flagcdn.com/w320/re.png",
  },
  {
    id: "SWZ",
    name: "Eswatini",
    capital: "Mbabane",
    flag: "https://flagcdn.com/w320/sz.png",
  },
  {
    id: "TJK",
    name: "Tajikistan",
    capital: "Dushanbe",
    flag: "https://flagcdn.com/w320/tj.png",
  },
  {
    id: "SAU",
    name: "Saudi Arabia",
    capital: "Riyadh",
    flag: "https://flagcdn.com/w320/sa.png",
  },
  {
    id: "BMU",
    name: "Bermuda",
    capital: "Hamilton",
    flag: "https://flagcdn.com/w320/bm.png",
  },
  {
    id: "NZL",
    name: "New Zealand",
    capital: "Wellington",
    flag: "https://flagcdn.com/w320/nz.png",
  },
  {
    id: "BLR",
    name: "Belarus",
    capital: "Minsk",
    flag: "https://flagcdn.com/w320/by.png",
  },
  {
    id: "CXR",
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    flag: "https://flagcdn.com/w320/cx.png",
  },
  {
    id: "GMB",
    name: "Gambia",
    capital: "Banjul",
    flag: "https://flagcdn.com/w320/gm.png",
  },
  {
    id: "PYF",
    name: "French Polynesia",
    capital: "Papeetē",
    flag: "https://flagcdn.com/w320/pf.png",
  },
  {
    id: "COD",
    name: "DR Congo",
    capital: "Kinshasa",
    flag: "https://flagcdn.com/w320/cd.png",
  },
  {
    id: "CRI",
    name: "Costa Rica",
    capital: "San José",
    flag: "https://flagcdn.com/w320/cr.png",
  },
  {
    id: "MWI",
    name: "Malawi",
    capital: "Lilongwe",
    flag: "https://flagcdn.com/w320/mw.png",
  },
  {
    id: "COG",
    name: "Republic of the Congo",
    capital: "Brazzaville",
    flag: "https://flagcdn.com/w320/cg.png",
  },
  {
    id: "OMN",
    name: "Oman",
    capital: "Muscat",
    flag: "https://flagcdn.com/w320/om.png",
  },
  {
    id: "IRQ",
    name: "Iraq",
    capital: "Baghdad",
    flag: "https://flagcdn.com/w320/iq.png",
  },
  {
    id: "NIU",
    name: "Niue",
    capital: "Alofi",
    flag: "https://flagcdn.com/w320/nu.png",
  },
  {
    id: "SEN",
    name: "Senegal",
    capital: "Dakar",
    flag: "https://flagcdn.com/w320/sn.png",
  },
  {
    id: "LBN",
    name: "Lebanon",
    capital: "Beirut",
    flag: "https://flagcdn.com/w320/lb.png",
  },
  {
    id: "AGO",
    name: "Angola",
    capital: "Luanda",
    flag: "https://flagcdn.com/w320/ao.png",
  },
  {
    id: "IRN",
    name: "Iran",
    capital: "Tehran",
    flag: "https://flagcdn.com/w320/ir.png",
  },
  {
    id: "ECU",
    name: "Ecuador",
    capital: "Quito",
    flag: "https://flagcdn.com/w320/ec.png",
  },
  {
    id: "LAO",
    name: "Laos",
    capital: "Vientiane",
    flag: "https://flagcdn.com/w320/la.png",
  },
  {
    id: "LKA",
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    flag: "https://flagcdn.com/w320/lk.png",
  },
  {
    id: "ABW",
    name: "Aruba",
    capital: "Oranjestad",
    flag: "https://flagcdn.com/w320/aw.png",
  },
  {
    id: "STP",
    name: "São Tomé and Príncipe",
    capital: "São Tomé",
    flag: "https://flagcdn.com/w320/st.png",
  },
  {
    id: "GRD",
    name: "Grenada",
    capital: "St. George's",
    flag: "https://flagcdn.com/w320/gd.png",
  },
  {
    id: "MSR",
    name: "Montserrat",
    capital: "Plymouth",
    flag: "https://flagcdn.com/w320/ms.png",
  },
  {
    id: "ESH",
    name: "Western Sahara",
    capital: "El Aaiún",
    flag: "https://flagcdn.com/w320/eh.png",
  },
  {
    id: "GIN",
    name: "Guinea",
    capital: "Conakry",
    flag: "https://flagcdn.com/w320/gn.png",
  },
  {
    id: "VGB",
    name: "British Virgin Islands",
    capital: "Road Town",
    flag: "https://flagcdn.com/w320/vg.png",
  },
  {
    id: "PAN",
    name: "Panama",
    capital: "Panama City",
    flag: "https://flagcdn.com/w320/pa.png",
  },
  {
    id: "YEM",
    name: "Yemen",
    capital: "Sana'a",
    flag: "https://flagcdn.com/w320/ye.png",
  },
  {
    id: "EST",
    name: "Estonia",
    capital: "Tallinn",
    flag: "https://flagcdn.com/w320/ee.png",
  },
  {
    id: "GUY",
    name: "Guyana",
    capital: "Georgetown",
    flag: "https://flagcdn.com/w320/gy.png",
  },
  {
    id: "LUX",
    name: "Luxembourg",
    capital: "Luxembourg",
    flag: "https://flagcdn.com/w320/lu.png",
  },
  {
    id: "NAM",
    name: "Namibia",
    capital: "Windhoek",
    flag: "https://flagcdn.com/w320/na.png",
  },
  {
    id: "UNK",
    name: "Kosovo",
    capital: "Pristina",
    flag: "https://flagcdn.com/w320/xk.png",
  },
  {
    id: "NCL",
    name: "New Caledonia",
    capital: "Nouméa",
    flag: "https://flagcdn.com/w320/nc.png",
  },
  {
    id: "SPM",
    name: "Saint Pierre and Miquelon",
    capital: "Saint-Pierre",
    flag: "https://flagcdn.com/w320/pm.png",
  },
  {
    id: "LBY",
    name: "Libya",
    capital: "Tripoli",
    flag: "https://flagcdn.com/w320/ly.png",
  },
  {
    id: "MMR",
    name: "Myanmar",
    capital: "Naypyidaw",
    flag: "https://flagcdn.com/w320/mm.png",
  },
  {
    id: "ISR",
    name: "Israel",
    capital: "Jerusalem",
    flag: "https://flagcdn.com/w320/il.png",
  },
  {
    id: "MLI",
    name: "Mali",
    capital: "Bamako",
    flag: "https://flagcdn.com/w320/ml.png",
  },
  {
    id: "ARG",
    name: "Argentina",
    capital: "Buenos Aires",
    flag: "https://flagcdn.com/w320/ar.png",
  },
  {
    id: "GUF",
    name: "French Guiana",
    capital: "Cayenne",
    flag: "https://flagcdn.com/w320/gf.png",
  },
  {
    id: "UGA",
    name: "Uganda",
    capital: "Kampala",
    flag: "https://flagcdn.com/w320/ug.png",
  },
  {
    id: "MYS",
    name: "Malaysia",
    capital: "Kuala Lumpur",
    flag: "https://flagcdn.com/w320/my.png",
  },
  {
    id: "ZMB",
    name: "Zambia",
    capital: "Lusaka",
    flag: "https://flagcdn.com/w320/zm.png",
  },
  {
    id: "FSM",
    name: "Micronesia",
    capital: "Palikir",
    flag: "https://flagcdn.com/w320/fm.png",
  },
  {
    id: "SVK",
    name: "Slovakia",
    capital: "Bratislava",
    flag: "https://flagcdn.com/w320/sk.png",
  },
  {
    id: "BDI",
    name: "Burundi",
    capital: "Gitega",
    flag: "https://flagcdn.com/w320/bi.png",
  },
  {
    id: "SRB",
    name: "Serbia",
    capital: "Belgrade",
    flag: "https://flagcdn.com/w320/rs.png",
  },
  {
    id: "TKM",
    name: "Turkmenistan",
    capital: "Ashgabat",
    flag: "https://flagcdn.com/w320/tm.png",
  },
  {
    id: "ZAF",
    name: "South Africa",
    capital: "Pretoria",
    flag: "https://flagcdn.com/w320/za.png",
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    capital: "Astana",
    flag: "https://flagcdn.com/w320/kz.png",
  },
  {
    id: "CAN",
    name: "Canada",
    capital: "Ottawa",
    flag: "https://flagcdn.com/w320/ca.png",
  },
  {
    id: "POL",
    name: "Poland",
    capital: "Warsaw",
    flag: "https://flagcdn.com/w320/pl.png",
  },
  {
    id: "PRI",
    name: "Puerto Rico",
    capital: "San Juan",
    flag: "https://flagcdn.com/w320/pr.png",
  },
  {
    id: "CCK",
    name: "Cocos (Keeling) Islands",
    capital: "West Island",
    flag: "https://flagcdn.com/w320/cc.png",
  },
  {
    id: "SMR",
    name: "San Marino",
    capital: "City of San Marino",
    flag: "https://flagcdn.com/w320/sm.png",
  },
  {
    id: "ASM",
    name: "American Samoa",
    capital: "Pago Pago",
    flag: "https://flagcdn.com/w320/as.png",
  },
  {
    id: "QAT",
    name: "Qatar",
    capital: "Doha",
    flag: "https://flagcdn.com/w320/qa.png",
  },
  {
    id: "GIB",
    name: "Gibraltar",
    capital: "Gibraltar",
    flag: "https://flagcdn.com/w320/gi.png",
  },
  {
    id: "HRV",
    name: "Croatia",
    capital: "Zagreb",
    flag: "https://flagcdn.com/w320/hr.png",
  },
  {
    id: "SJM",
    name: "Svalbard and Jan Mayen",
    capital: "Longyearbyen",
    flag: "https://flagcdn.com/w320/sj.png",
  },
  {
    id: "IMN",
    name: "Isle of Man",
    capital: "Douglas",
    flag: "https://flagcdn.com/w320/im.png",
  },
  {
    id: "PSE",
    name: "Palestine",
    capital: "Ramallah",
    flag: "https://flagcdn.com/w320/ps.png",
  },
  {
    id: "MUS",
    name: "Mauritius",
    capital: "Port Louis",
    flag: "https://flagcdn.com/w320/mu.png",
  },
  {
    id: "MAF",
    name: "Saint Martin",
    capital: "Marigot",
    flag: "https://flagcdn.com/w320/mf.png",
  },
  {
    id: "SLE",
    name: "Sierra Leone",
    capital: "Freetown",
    flag: "https://flagcdn.com/w320/sl.png",
  },
  {
    id: "KNA",
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    flag: "https://flagcdn.com/w320/kn.png",
  },
  {
    id: "ISL",
    name: "Iceland",
    capital: "Reykjavik",
    flag: "https://flagcdn.com/w320/is.png",
  },

  {
    id: "KWT",
    name: "Kuwait",
    capital: "Kuwait City",
    flag: "https://flagcdn.com/w320/kw.png",
  },
  {
    id: "TWN",
    name: "Taiwan",
    capital: "Taipei",
    flag: "https://flagcdn.com/w320/tw.png",
  },
  {
    id: "CMR",
    name: "Cameroon",
    capital: "Yaoundé",
    flag: "https://flagcdn.com/w320/cm.png",
  },
  {
    id: "SLV",
    name: "El Salvador",
    capital: "San Salvador",
    flag: "https://flagcdn.com/w320/sv.png",
  },

  {
    id: "CUB",
    name: "Cuba",
    capital: "Havana",
    flag: "https://flagcdn.com/w320/cu.png",
  },
  {
    id: "BRA",
    name: "Brazil",
    capital: "Brasília",
    flag: "https://flagcdn.com/w320/br.png",
  },
  {
    id: "SLB",
    name: "Solomon Islands",
    capital: "Honiara",
    flag: "https://flagcdn.com/w320/sb.png",
  },
  {
    id: "GRC",
    name: "Greece",
    capital: "Athens",
    flag: "https://flagcdn.com/w320/gr.png",
  },
  {
    id: "NOR",
    name: "Norway",
    capital: "Oslo",
    flag: "https://flagcdn.com/w320/no.png",
  },
  {
    id: "JAM",
    name: "Jamaica",
    capital: "Kingston",
    flag: "https://flagcdn.com/w320/jm.png",
  },
  {
    id: "TZA",
    name: "Tanzania",
    capital: "Dodoma",
    flag: "https://flagcdn.com/w320/tz.png",
  },
  {
    id: "BOL",
    name: "Bolivia",
    capital: "Sucre",
    flag: "https://flagcdn.com/w320/bo.png",
  },
  {
    id: "CYP",
    name: "Cyprus",
    capital: "Nicosia",
    flag: "https://flagcdn.com/w320/cy.png",
  },
  {
    id: "MNG",
    name: "Mongolia",
    capital: "Ulan Bator",
    flag: "https://flagcdn.com/w320/mn.png",
  },
  {
    id: "MCO",
    name: "Monaco",
    capital: "Monaco",
    flag: "https://flagcdn.com/w320/mc.png",
  },
  {
    id: "TUN",
    name: "Tunisia",
    capital: "Tunis",
    flag: "https://flagcdn.com/w320/tn.png",
  },
  {
    id: "ATF",
    name: "French Southern and Antarctic Lands",
    capital: "Port-aux-Français",
    flag: "https://flagcdn.com/w320/tf.png",
  },
  {
    id: "SYR",
    name: "Syria",
    capital: "Damascus",
    flag: "https://flagcdn.com/w320/sy.png",
  },
  {
    id: "CHL",
    name: "Chile",
    capital: "Santiago",
    flag: "https://flagcdn.com/w320/cl.png",
  },
  {
    id: "AZE",
    name: "Azerbaijan",
    capital: "Baku",
    flag: "https://flagcdn.com/w320/az.png",
  },
  {
    id: "FRA",
    name: "France",
    capital: "Paris",
    flag: "https://flagcdn.com/w320/fr.png",
  },
  {
    id: "KOR",
    name: "South Korea",
    capital: "Seoul",
    flag: "https://flagcdn.com/w320/kr.png",
  },
  {
    id: "GHA",
    name: "Ghana",
    capital: "Accra",
    flag: "https://flagcdn.com/w320/gh.png",
  },
  {
    id: "DNK",
    name: "Denmark",
    capital: "Copenhagen",
    flag: "https://flagcdn.com/w320/dk.png",
  },
  {
    id: "SXM",
    name: "Sint Maarten",
    capital: "Philipsburg",
    flag: "https://flagcdn.com/w320/sx.png",
  },
  {
    id: "AND",
    name: "Andorra",
    capital: "Andorra la Vella",
    flag: "https://flagcdn.com/w320/ad.png",
  },
  {
    id: "CUW",
    name: "Curaçao",
    capital: "Willemstad",
    flag: "https://flagcdn.com/w320/cw.png",
  },
  {
    id: "CHE",
    name: "Switzerland",
    capital: "Bern",
    flag: "https://flagcdn.com/w320/ch.png",
  },
  {
    id: "MKD",
    name: "North Macedonia",
    capital: "Skopje",
    flag: "https://flagcdn.com/w320/mk.png",
  },
  {
    id: "SSD",
    name: "South Sudan",
    capital: "Juba",
    flag: "https://flagcdn.com/w320/ss.png",
  },
  {
    id: "HTI",
    name: "Haiti",
    capital: "Port-au-Prince",
    flag: "https://flagcdn.com/w320/ht.png",
  },
  {
    id: "PER",
    name: "Peru",
    capital: "Lima",
    flag: "https://flagcdn.com/w320/pe.png",
  },
  {
    id: "GNB",
    name: "Guinea-Bissau",
    capital: "Bissau",
    flag: "https://flagcdn.com/w320/gw.png",
  },
  {
    id: "CZE",
    name: "Czechia",
    capital: "Prague",
    flag: "https://flagcdn.com/w320/cz.png",
  },
  {
    id: "PRT",
    name: "Portugal",
    capital: "Lisbon",
    flag: "https://flagcdn.com/w320/pt.png",
  },
  {
    id: "GAB",
    name: "Gabon",
    capital: "Libreville",
    flag: "https://flagcdn.com/w320/ga.png",
  },
  {
    id: "MEX",
    name: "Mexico",
    capital: "Mexico City",
    flag: "https://flagcdn.com/w320/mx.png",
  },
  {
    id: "ITA",
    name: "Italy",
    capital: "Rome",
    flag: "https://flagcdn.com/w320/it.png",
  },
  {
    id: "FIN",
    name: "Finland",
    capital: "Helsinki",
    flag: "https://flagcdn.com/w320/fi.png",
  },
  {
    id: "ZWE",
    name: "Zimbabwe",
    capital: "Harare",
    flag: "https://flagcdn.com/w320/zw.png",
  },
  {
    id: "ESP",
    name: "Spain",
    capital: "Madrid",
    flag: "https://flagcdn.com/w320/es.png",
  },
  {
    id: "JPN",
    name: "Japan",
    capital: "Tokyo",
    flag: "https://flagcdn.com/w320/jp.png",
  },
  {
    id: "SYC",
    name: "Seychelles",
    capital: "Victoria",
    flag: "https://flagcdn.com/w320/sc.png",
  },
  {
    id: "ALB",
    name: "Albania",
    capital: "Tirana",
    flag: "https://flagcdn.com/w320/al.png",
  },
  {
    id: "MDA",
    name: "Moldova",
    capital: "Chișinău",
    flag: "https://flagcdn.com/w320/md.png",
  },
  {
    id: "GTM",
    name: "Guatemala",
    capital: "Guatemala City",
    flag: "https://flagcdn.com/w320/gt.png",
  },
  {
    id: "DEU",
    name: "Germany",
    capital: "Berlin",
    flag: "https://flagcdn.com/w320/de.png",
  },
  {
    id: "GLP",
    name: "Guadeloupe",
    capital: "Basse-Terre",
    flag: "https://flagcdn.com/w320/gp.png",
  },
  {
    id: "BGR",
    name: "Bulgaria",
    capital: "Sofia",
    flag: "https://flagcdn.com/w320/bg.png",
  },
  {
    id: "PRY",
    name: "Paraguay",
    capital: "Asunción",
    flag: "https://flagcdn.com/w320/py.png",
  },
  {
    id: "ERI",
    name: "Eritrea",
    capital: "Asmara",
    flag: "https://flagcdn.com/w320/er.png",
  },
  {
    id: "SDN",
    name: "Sudan",
    capital: "Khartoum",
    flag: "https://flagcdn.com/w320/sd.png",
  },
  {
    id: "GNQ",
    name: "Equatorial Guinea",
    capital: "Malabo",
    flag: "https://flagcdn.com/w320/gq.png",
  },
  {
    id: "COL",
    name: "Colombia",
    capital: "Bogotá",
    flag: "https://flagcdn.com/w320/co.png",
  },
  {
    id: "NGA",
    name: "Nigeria",
    capital: "Abuja",
    flag: "https://flagcdn.com/w320/ng.png",
  },
  {
    id: "MNE",
    name: "Montenegro",
    capital: "Podgorica",
    flag: "https://flagcdn.com/w320/me.png",
  },
  {
    id: "NPL",
    name: "Nepal",
    capital: "Kathmandu",
    flag: "https://flagcdn.com/w320/np.png",
  },
  {
    id: "BRN",
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    flag: "https://flagcdn.com/w320/bn.png",
  },
  {
    id: "AUT",
    name: "Austria",
    capital: "Vienna",
    flag: "https://flagcdn.com/w320/at.png",
  },
  {
    id: "TCA",
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    flag: "https://flagcdn.com/w320/tc.png",
  },
  {
    id: "BHS",
    name: "Bahamas",
    capital: "Nassau",
    flag: "https://flagcdn.com/w320/bs.png",
  },
  {
    id: "GBR",
    name: "United Kingdom",
    capital: "London",
    flag: "https://flagcdn.com/w320/gb.png",
  },
  {
    id: "IOT",
    name: "British Indian Ocean Territory",
    capital: "Diego Garcia",
    flag: "https://flagcdn.com/w320/io.png",
  },
  {
    id: "LBR",
    name: "Liberia",
    capital: "Monrovia",
    flag: "https://flagcdn.com/w320/lr.png",
  },
  {
    id: "AIA",
    name: "Anguilla",
    capital: "The Valley",
    flag: "https://flagcdn.com/w320/ai.png",
  },
  {
    id: "CAF",
    name: "Central African Republic",
    capital: "Bangui",
    flag: "https://flagcdn.com/w320/cf.png",
  },
  {
    id: "DZA",
    name: "Algeria",
    capital: "Algiers",
    flag: "https://flagcdn.com/w320/dz.png",
  },
  {
    id: "LCA",
    name: "Saint Lucia",
    capital: "Castries",
    flag: "https://flagcdn.com/w320/lc.png",
  },
  {
    id: "ROU",
    name: "Romania",
    capital: "Bucharest",
    flag: "https://flagcdn.com/w320/ro.png",
  },
  {
    id: "ARE",
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    flag: "https://flagcdn.com/w320/ae.png",
  },
  {
    id: "MAR",
    name: "Morocco",
    capital: "Rabat",
    flag: "https://flagcdn.com/w320/ma.png",
  },
  {
    id: "MNP",
    name: "Northern Mariana Islands",
    capital: "Saipan",
    flag: "https://flagcdn.com/w320/mp.png",
  },
  {
    id: "UMI",
    name: "United States Minor Outlying Islands",
    capital: "Washington DC",
    flag: "https://flagcdn.com/w320/um.png",
  },
  {
    id: "BWA",
    name: "Botswana",
    capital: "Gaborone",
    flag: "https://flagcdn.com/w320/bw.png",
  },
  {
    id: "LTU",
    name: "Lithuania",
    capital: "Vilnius",
    flag: "https://flagcdn.com/w320/lt.png",
  },
  {
    id: "BES",
    name: "Caribbean Netherlands",
    capital: "Kralendijk",
    flag: "https://flagcdn.com/w320/bq.png",
  },
  {
    id: "CPV",
    name: "Cape Verde",
    capital: "Praia",
    flag: "https://flagcdn.com/w320/cv.png",
  },
  {
    id: "USA",
    name: "United States",
    capital: "Washington, D.C.",
    flag: "https://flagcdn.com/w320/us.png",
  },
  {
    id: "AUS",
    name: "Australia",
    capital: "Canberra",
    flag: "https://flagcdn.com/w320/au.png",
  },
  {
    id: "GUM",
    name: "Guam",
    capital: "Hagåtña",
    flag: "https://flagcdn.com/w320/gu.png",
  },
  {
    id: "TON",
    name: "Tonga",
    capital: "Nuku'alofa",
    flag: "https://flagcdn.com/w320/to.png",
  },
  {
    id: "AFG",
    name: "Afghanistan",
    capital: "Kabul",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
  },
  {
    id: "FLK",
    name: "Falkland Islands",
    capital: "Stanley",
    flag: "https://flagcdn.com/w320/fk.png",
  },
  {
    id: "NRU",
    name: "Nauru",
    capital: "Yaren",
    flag: "https://flagcdn.com/w320/nr.png",
  },
  {
    id: "COK",
    name: "Cook Islands",
    capital: "Avarua",
    flag: "https://flagcdn.com/w320/ck.png",
  },
  {
    id: "HUN",
    name: "Hungary",
    capital: "Budapest",
    flag: "https://flagcdn.com/w320/hu.png",
  },
  {
    id: "MRT",
    name: "Mauritania",
    capital: "Nouakchott",
    flag: "https://flagcdn.com/w320/mr.png",
  },
  {
    id: "SVN",
    name: "Slovenia",
    capital: "Ljubljana",
    flag: "https://flagcdn.com/w320/si.png",
  },
  {
    id: "TCD",
    name: "Chad",
    capital: "N'Djamena",
    flag: "https://flagcdn.com/w320/td.png",
  },
  {
    id: "VAT",
    name: "Vatican City",
    capital: "Vatican City",
    flag: "https://flagcdn.com/w320/va.png",
  },
  {
    id: "BEN",
    name: "Benin",
    capital: "Porto-Novo",
    flag: "https://flagcdn.com/w320/bj.png",
  },
  {
    id: "SGP",
    name: "Singapore",
    capital: "Singapore",
    flag: "https://flagcdn.com/w320/sg.png",
  },
  {
    id: "MLT",
    name: "Malta",
    capital: "Valletta",
    flag: "https://flagcdn.com/w320/mt.png",
  },
  {
    id: "VCT",
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    flag: "https://flagcdn.com/w320/vc.png",
  },
  {
    id: "MHL",
    name: "Marshall Islands",
    capital: "Majuro",
    flag: "https://flagcdn.com/w320/mh.png",
  },
  {
    id: "THA",
    name: "Thailand",
    capital: "Bangkok",
    flag: "https://flagcdn.com/w320/th.png",
  },
  {
    id: "LIE",
    name: "Liechtenstein",
    capital: "Vaduz",
    flag: "https://flagcdn.com/w320/li.png",
  },
  {
    id: "IRL",
    name: "Ireland",
    capital: "Dublin",
    flag: "https://flagcdn.com/w320/ie.png",
  },
  {
    id: "MDV",
    name: "Maldives",
    capital: "Malé",
    flag: "https://flagcdn.com/w320/mv.png",
  },
  {
    id: "VNM",
    name: "Vietnam",
    capital: "Hanoi",
    flag: "https://flagcdn.com/w320/vn.png",
  },
  {
    id: "ARM",
    name: "Armenia",
    capital: "Yerevan",
    flag: "https://flagcdn.com/w320/am.png",
  },
  {
    id: "PAK",
    name: "Pakistan",
    capital: "Islamabad",
    flag: "https://flagcdn.com/w320/pk.png",
  },
  {
    id: "CIV",
    name: "Ivory Coast",
    capital: "Yamoussoukro",
    flag: "https://flagcdn.com/w320/ci.png",
  },
  {
    id: "RUS",
    name: "Russia",
    capital: "Moscow",
    flag: "https://flagcdn.com/w320/ru.png",
  },
  {
    id: "MTQ",
    name: "Martinique",
    capital: "Fort-de-France",
    flag: "https://flagcdn.com/w320/mq.png",
  },

  {
    id: "TLS",
    name: "Timor-Leste",
    capital: "Dili",
    flag: "https://flagcdn.com/w320/tl.png",
  },
  {
    id: "NIC",
    name: "Nicaragua",
    capital: "Managua",
    flag: "https://flagcdn.com/w320/ni.png",
  },
  {
    id: "PNG",
    name: "Papua New Guinea",
    capital: "Port Moresby",
    flag: "https://flagcdn.com/w320/pg.png",
  },
  {
    id: "EGY",
    name: "Egypt",
    capital: "Cairo",
    flag: "https://flagcdn.com/w320/eg.png",
  },
  {
    id: "JOR",
    name: "Jordan",
    capital: "Amman",
    flag: "https://flagcdn.com/w320/jo.png",
  },
  {
    id: "URY",
    name: "Uruguay",
    capital: "Montevideo",
    flag: "https://flagcdn.com/w320/uy.png",
  },
  {
    id: "BFA",
    name: "Burkina Faso",
    capital: "Ouagadougou",
    flag: "https://flagcdn.com/w320/bf.png",
  },
  {
    id: "KHM",
    name: "Cambodia",
    capital: "Phnom Penh",
    flag: "https://flagcdn.com/w320/kh.png",
  },
  {
    id: "ETH",
    name: "Ethiopia",
    capital: "Addis Ababa",
    flag: "https://flagcdn.com/w320/et.png",
  },
  {
    id: "KIR",
    name: "Kiribati",
    capital: "South Tarawa",
    flag: "https://flagcdn.com/w320/ki.png",
  },
  {
    id: "BTN",
    name: "Bhutan",
    capital: "Thimphu",
    flag: "https://flagcdn.com/w320/bt.png",
  },
  {
    id: "DOM",
    name: "Dominican Republic",
    capital: "Santo Domingo",
    flag: "https://flagcdn.com/w320/do.png",
  },
  {
    id: "SUR",
    name: "Suriname",
    capital: "Paramaribo",
    flag: "https://flagcdn.com/w320/sr.png",
  },
  {
    id: "BGD",
    name: "Bangladesh",
    capital: "Dhaka",
    flag: "https://flagcdn.com/w320/bd.png",
  },
  {
    id: "BRB",
    name: "Barbados",
    capital: "Bridgetown",
    flag: "https://flagcdn.com/w320/bb.png",
  },
  {
    id: "PRK",
    name: "North Korea",
    capital: "Pyongyang",
    flag: "https://flagcdn.com/w320/kp.png",
  },
  {
    id: "GRL",
    name: "Greenland",
    capital: "Nuuk",
    flag: "https://flagcdn.com/w320/gl.png",
  },
  {
    id: "BEL",
    name: "Belgium",
    capital: "Brussels",
    flag: "https://flagcdn.com/w320/be.png",
  },
  {
    id: "PLW",
    name: "Palau",
    capital: "Ngerulmud",
    flag: "https://flagcdn.com/w320/pw.png",
  },
  {
    id: "NFK",
    name: "Norfolk Island",
    capital: "Kingston",
    flag: "https://flagcdn.com/w320/nf.png",
  },
  {
    id: "SGS",
    name: "South Georgia",
    capital: "King Edward Point",
    flag: "https://flagcdn.com/w320/gs.png",
  },
  {
    id: "PHL",
    name: "Philippines",
    capital: "Manila",
    flag: "https://flagcdn.com/w320/ph.png",
  },
  {
    id: "IND",
    name: "India",
    capital: "New Delhi",
    flag: "https://flagcdn.com/w320/in.png",
  },
  {
    id: "IDN",
    name: "Indonesia",
    capital: "Jakarta",
    flag: "https://flagcdn.com/w320/id.png",
  },
  {
    id: "VIR",
    name: "United States Virgin Islands",
    capital: "Charlotte Amalie",
    flag: "https://flagcdn.com/w320/vi.png",
  },
  {
    id: "DMA",
    name: "Dominica",
    capital: "Roseau",
    flag: "https://flagcdn.com/w320/dm.png",
  },
  {
    id: "RWA",
    name: "Rwanda",
    capital: "Kigali",
    flag: "https://flagcdn.com/w320/rw.png",
  },
  {
    id: "MDG",
    name: "Madagascar",
    capital: "Antananarivo",
    flag: "https://flagcdn.com/w320/mg.png",
  },
  {
    id: "HKG",
    name: "Hong Kong",
    capital: "City of Victoria",
    flag: "https://flagcdn.com/w320/hk.png",
  },
  {
    id: "WSM",
    name: "Samoa",
    capital: "Apia",
    flag: "https://flagcdn.com/w320/ws.png",
  },
  {
    id: "FRO",
    name: "Faroe Islands",
    capital: "Tórshavn",
    flag: "https://flagcdn.com/w320/fo.png",
  },
  {
    id: "PCN",
    name: "Pitcairn Islands",
    capital: "Adamstown",
    flag: "https://flagcdn.com/w320/pn.png",
  },
  {
    id: "ATG",
    name: "Antigua and Barbuda",
    capital: "Saint John's",
    flag: "https://flagcdn.com/w320/ag.png",
  },
  {
    id: "ALA",
    name: "Åland Islands",
    capital: "Mariehamn",
    flag: "https://flagcdn.com/w320/ax.png",
  },
  {
    id: "SWE",
    name: "Sweden",
    capital: "Stockholm",
    flag: "https://flagcdn.com/w320/se.png",
  },
  {
    id: "MOZ",
    name: "Mozambique",
    capital: "Maputo",
    flag: "https://flagcdn.com/w320/mz.png",
  },
  {
    id: "UZB",
    name: "Uzbekistan",
    capital: "Tashkent",
    flag: "https://flagcdn.com/w320/uz.png",
  },

  {
    id: "WLF",
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    flag: "https://flagcdn.com/w320/wf.png",
  },
  {
    id: "UKR",
    name: "Ukraine",
    capital: "Kyiv",
    flag: "https://flagcdn.com/w320/ua.png",
  },
  {
    id: "BLZ",
    name: "Belize",
    capital: "Belmopan",
    flag: "https://flagcdn.com/w320/bz.png",
  },
  {
    id: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    capital: "Jamestown",
    flag: "https://flagcdn.com/w320/sh.png",
  },
  {
    id: "GGY",
    name: "Guernsey",
    capital: "St. Peter Port",
    flag: "https://flagcdn.com/w320/gg.png",
  },
  {
    id: "TKL",
    name: "Tokelau",
    capital: "Fakaofo",
    flag: "https://flagcdn.com/w320/tk.png",
  },
];
